Rewrite Windows components in Rust
nullpo-head/WSL-Hello-sudo pull request #26
Opened 2021-10-29 04:39 UTC by BlackHoleFox

This simplifies the build toolchain, build and packaging steps, implementation, and some other things.

Building, installing, creation, and authentication tested in WSL Ubuntu 18 with Win 10 Pro.

2021-11-02 14:42 UTC, nullpo-head commented
wow!! Thanks so much for your contribution! Let me take a look at a little while later when I have time

2021-11-16 15:59 UTC, nullpo-head requested changes
Thanks for your awesome work. Rewriting them in Rust was what I wanted to try but I wasn't able to accomplish. I've added some review comments to proceed with this rewriting project. Thanks!

2021-11-16 15:59 UTC, nullpo-head commented on README.md
> +> Whether you're using `bash` or Windows, the repository must be in the Windows filesystem, otherwise `cargo` on Windows won't work.
I guess cargo.exe works on WSL's filesystem as well. So maybe this sentence isn't necessary anymore?

2021-11-16 15:59 UTC, nullpo-head commented on win_hello_bridge/build.rs
> +}
I don't have so much experience on windows-rs yet, but why is this `build.rs` required? Isn't it possible to just update `cargo.toml` as follows?

```toml
[dependencies.windows]
version = "0.27.0"
features = [
    "std",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
]
```

2021-11-16 15:59 UTC, nullpo-head commented on Makefile
> +
I think just `cargo.exe` works because it should be in the PATH on Windows as well.

2021-11-16 15:59 UTC, nullpo-head commented on win_hello_bridge/src/authenticator.rs
> +        .unwrap()
Hi! Your rewriting work looks overall awesome! Could you extend `Unknown` reason or add a new error that takes an inner error, and convert those `unwrap` to `?` operator? Like `Unknown(Error)`

2021-11-16 16:02 UTC, nullpo-head requested changes
This

2021-11-16 16:02 UTC, nullpo-head commented on win_components/Makefile
> -.PHONY: all clean
We need a Makefile for Windows (or, make sure the main Makefile works on both Windows and Linux) so that the CI/CD pipeline works. Please look at the yaml under .github/workflow and update it so that CI will continue to work.

2021-11-16 17:05 UTC, jonaskuske commented on Makefile
> +
Not if you have
```ini
[interop]
appendWindowsPath = false
```
in your `/etc/wsl.conf`, e.g. because there are conflicting binaries/versions in your Windows and Linux env

2021-11-16 17:53 UTC, BlackHoleFox commented on Makefile
> +
So this is super convoluted for a different reason: Supporting building both the Windows binaries and PAM `.so` from inside WSL. Both the Windows cargo.exe and WSL `cargo` ELF are needed.

2021-11-16 17:54 UTC, BlackHoleFox commented on win_components/Makefile
> -.PHONY: all clean
This looks like a dependency issue now that we're building `openssl-sys` on Windows too because of the workspace. Easy fix is probably to use the `vendored` feature of `openssl-sys`. I'll try this out a bit later.

2021-11-16 17:54 UTC, BlackHoleFox commented on win_hello_bridge/build.rs
> +}
Yeah ill switch this to the new `windows` version that's prebuilt. When I originally wrote this it wasn't out yet.

2021-11-17 00:05 UTC, BlackHoleFox commented on README.md
> +> Whether you're using `bash` or Windows, the repository must be in the Windows filesystem, otherwise `cargo` on Windows won't work.
Ive deleted it.

2021-11-17 00:06 UTC, BlackHoleFox commented on win_hello_bridge/build.rs
> +}
Switched.

2021-11-17 00:06 UTC, BlackHoleFox commented on win_hello_bridge/src/authenticator.rs
> +        .unwrap()
I made an `Other` variant to handle these generic WinRT errors. All the unwraps are now gone.

2021-11-17 00:07 UTC, BlackHoleFox commented on win_components/Makefile
> -.PHONY: all clean
@nullpo-head Please try running the CI again. The build failure should be fixed with https://github.com/nullpo-head/WSL-Hello-sudo/pull/26/commits/4d403b568d8b08104cb7fb5ea3a7b5a548406c73

2021-11-23 14:29 UTC, nullpo-head commented on Makefile
> +
>  Supporting building both the Windows binaries and PAM .so from inside WSL.

In that respect, we are on the same page. The point is whether the way to invoke `cargo.exe` is too complicated or not. 

@jonaskuske 's comment is understandable, but I think we can assume that they have Windows PATH in WSL because it is the default behavior of WSL. Even if it is opted-out, the user is aware of that and they can figure out why the build fails soon.

On the other hand, `wslvar` command is the part of wslutility tools, which is not installed on other distros than Ubuntu 20.04. I don't think it's reasonable to assume that developers always use Ubuntu 20.04 but may not have `appendWindowsPath` enabled. 

So, my opinion is just using `cargo.exe` is better. It should succeed to build, if I'm not missing something. What do you think?

2021-11-23 14:32 UTC, nullpo-head commented on win_components/Makefile
> -.PHONY: all clean
Hi, I've rerun the CI. BTW, could you rebase the master branch to your branch, please? I made a change to CI so that it builds the release asset of pull requests. So, once you succeed to fix the CI, it will also output the release build, which you can use for testing.

2021-11-23 17:54 UTC, BlackHoleFox commented on win_components/Makefile
> -.PHONY: all clean
I ran the CI steps locally in Git Bash and it seems to be good now.

btw, CI might make a release build automatically but due to GitHub's "first contributor" CI rules, it will never run for me automatically before I merge my first PR.

2021-11-23 17:55 UTC, BlackHoleFox commented on Makefile
> +
I had given `cargo.exe` a try originally, but it doesn't seem to be getting put on the WSL path. I see this building in WSL:
```
cargo.exe build -p win_hello_bridge --release
make: cargo.exe: Command not found
```

Might just be doing it wrong, but I can't get `cargo.exe` to work regardless of my `appendWindowsPath` setting.

2021-11-23 18:11 UTC, nullpo-head commented on Makefile
> +
Thanks for your quick response! That's because you don't have the path to cargo's bin in your Windows' environment variables. `rustup` should do that automatically unless you opted out, or you installed Rust so long time ago.

2021-11-23 18:29 UTC, BlackHoleFox commented on Makefile
> +
It should be in my Windows env. I can use `cargo` and `cargo.exe` from Powershell fine.

2021-11-24 06:46 UTC, BlackHoleFox commented
It looks like the last CI issue (the Windows binary name one is trivial) will be getting the semantic versioning job to update both `Cargo.toml` files...

2021-11-27 06:37 UTC, BlackHoleFox commented
@nullpo-head Please run the CI again when you get a chance. Things should be working now.

2021-11-27 11:29 UTC, nullpo-head commented on Makefile
> +
In general, if your Windows "`PATH`" has the path to cargo\bin, then WSL should have it in its PATH, too. If not, I guess it's something special in your environment, so could you investigate why please? IMHO, `wslvar` command is far uncommon one than that problem. It's available by default only on Ubuntu installed from Microsoft store. Other distros such as Debian on the store, or all distros including Ubuntu installed from custom installers such as ArchWSL or my [Distrod project](https://github.com/nullpo-head/wsl-distrod) don't have `wslvar` either. So, asking developers to set the path to Windows cargo in `PATH` is more user-friendly and simpler.

2021-11-27 11:30 UTC, nullpo-head commented
> @nullpo-head Please run the CI again when you get a chance. Things should be working now.

Thanks so much! Now with a little few changes  I'll merge this soon.

2021-11-28 02:29 UTC, BlackHoleFox commented on Makefile
> +
That sounds fine since `wslvar` is so uncommon. Its now hardcoded to `cargo.exe`.

2021-11-29 15:51 UTC, nullpo-head commented on Makefile
> +
Thansk!

2021-11-29 15:58 UTC, nullpo-head commented on install.sh
>  fi
The last work for v2.0.0 release .... Could you add another elif clause that replaces `WindowsHelloAuthenticator.exe` with ` WindowsHelloBridge.exe` 1. if the config file exists, 2. and it contains `WindowsHelloAuthenticator`, saying that it updates the Windows component. Basically, I'd like to update this installer script so that it supports the update from v1.4.0 to your v2.0.0

2021-11-29 17:29 UTC, nullpo-head commented on install.sh
>  fi
That sounds a good idea to me

2021-11-30 04:22 UTC, BlackHoleFox commented on install.sh
>  fi
I added both the config and install location migrations in the latest commit. Let me know if theres something that could be improved, bash isn't my favorite.

2021-12-03 16:59 UTC, nullpo-head requested changes

2021-12-03 16:59 UTC, nullpo-head commented on install.sh
> +  sed -i "1s/.*/$AUTHENTICATOR_PATH/" "$PAM_CONFIG_FILENAME"
This causes the following error because `$AUTHENTICATOR_PATH` contains `/`. Let's update the sed command.

```console
sed: -e expression #1, char 31: unknown option to `s'
```

```suggestion
  sed -i "1s;.*;$AUTHENTICATOR_PATH;" "$PAM_CONFIG_FILENAME"
```

2021-12-03 17:34 UTC, nullpo-head requested changes

2021-12-03 17:34 UTC, nullpo-head commented on install.sh
> +  sudo sed -i "1s;.*;$AUTHENTICATOR_PATH;" "$PAM_CONFIG_FILENAME"
`.*` looks a bit too general. Let's make it more explicit.

```suggestion
  sudo sed -i "1s;authenticator_path.*;$AUTHENTICATOR_PATH;" "$PAM_CONFIG_FILENAME"
```

2021-12-03 17:43 UTC, nullpo-head approved these changes
Looks good to me. Thanks so much for your contribution!! I'll merge this PR soon!

2021-12-04 04:11 UTC, merged

2021-12-04 04:16 UTC, nullpo-head commented
Now v2.0.0 has been releasaed! Kudos to @BlackHoleFox !!